apiVersion: 1

datasources:
  - name: DuckDB Query API
    uid: duckdb-query-api
    type: yesoreyeram-infinity-datasource
    access: proxy
    url: http://duckdb-query-api:8000
    isDefault: true
    editable: true
